# Generated by Django 4.2.16 on 2024-10-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0002_alter_part_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitem',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
