# Generated by Django 4.2.16 on 2024-10-15 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0003_partitem_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droneitem',
            name='drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='drone.drone'),
        ),
    ]
